DATA SEGMENT
DATA ENDS
STACKS SEGMENT
STACKS ENDS
CODES SEGMENT
    ASSUME CS:CODES,DS:DATA,SS:STACKS
START:
    MOV AX,DATA
    MOV DS,AX  
    MOV AH,00H
    MOV AL,02H
    INT 10H
    MOV AH,09H
    MOV BH,0
    MOV AL,'H'
    MOV BL,04H;字符为红色
    MOV CX,5;显示五个字符
    INT 10H   ;前景色为红色
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START
